---
title: "choropleth_map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(data.table)
library(plotly)
library(tidyverse)
library(tidycensus) # population data from 2019
```

# Covid State data
```{r}
state_data <- fread('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv')
str(state_data)
```
## Covidcast state-level population data
```{r}
library(covidcast)
str(state_census)
```
# Data Preparation

```{r}
# Single date - most recent
FILTER_DATE = max(state_data$date)

# Filter data
state_data_filtered <- state_data %>% 
   filter(date == FILTER_DATE) %>% 
   select(date, state, fips, cases, deaths) 

# Join on fips to get covid and population data
state_pop_data <- left_join(state_data_filtered,state_census, by=c("fips"="STATE")) %>%
   select(date, state, fips, cases, deaths, POPESTIMATE2019)

# cases and deaths per 10k people
state_dataplot <- state_pop_data %>% 
   mutate(state.abbreviation = state.abb[match(state,state.name)]) %>%
   mutate(cases.per10000 = cases/ POPESTIMATE2019 * 10000) %>% 
   mutate(deaths.per10000 = deaths/ POPESTIMATE2019 * 10000) %>%
   select(fips, state.abbreviation, cases.per10000, deaths.per10000) 
state_dataplot

```
# Plotly choropleth
```{r}
library(plotly)
df <- state_dataplot

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 10)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

fig <- plot_geo(df, locationmode = 'USA-states')
fig <- fig %>% add_trace(
    type="choropleth",
    locations=df$state.abbreviation,
    z=df$cases.per10000,
    colorscale="Hot",
    reversescale = TRUE,
    marker=list(line=list(
      width=0)
    )
  )
# fig <- fig %>% colorbar(title = "Millions USD")
fig <- fig %>% layout(
    geo = g
  )

fig
```

# County-level data
## County-level Covid-19 data from NYTimes
```{r}
county_data <- fread('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
county_data$fips <- sprintf("%05d", county_data$fips)
str(county_data)
```

## County-level population data
```{r}
county_pop_data <- fread('./census-est2021-alldata.csv')

state_conversion <- function(x) {sprintf("%02d", x)}
county_conversion <- function(x) {sprintf("%03d", x)}

county_pop_data_processed <- county_pop_data %>% 
  select(STATE, COUNTY, STNAME, CTYNAME, POPESTIMATE2020) %>%
  mutate(FIPS = paste0(state_conversion(STATE), county_conversion(COUNTY)))
```

```{r}
counties_final <- left_join(county_data, county_pop_data_processed, by = c("fips" = "FIPS")) %>%
   select(date, county, state, fips, cases, deaths, POPESTIMATE2020) %>%
   mutate(cases.per10000 = cases/ POPESTIMATE2020 * 10000) %>% 
   mutate(deaths.per10000 = deaths/ POPESTIMATE2020 * 10000) %>%
   filter(!is.na(POPESTIMATE2020))
str(counties_final)
```

```{r}
library(plotly)
library(rjson)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
fig <- plot_ly()
fig <- fig %>% add_trace(
    type="choropleth",
    geojson=counties,
    locations=counties_final$fips,
    z=counties_final$cases.per10000,
    colorscale="Viridis",
    marker=list(line=list(
      width=0)
    )
  )
# fig <- fig %>% colorbar(title = "Unemployment Rate (%)")
fig <- fig %>% layout(
    title = "2016 US Unemployment by County"
)

fig <- fig %>% layout(
    geo = g
  )

fig
```

